version: '3.9'

services:
  db:
    image: postgres:16.0
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: daphne core.asgi:application --port 8000 --bind 0.0.0.0 -v 3
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "1337:80"
    depends_on:
      - web

  redis:
    build: redis
    container_name: redis_server
    expose:
      - 6379

volumes:
  postgres_data:
  static_volume:
  media_volume:
